runtime: php82

handlers:
# # Serve a directory as a static resource.
# - url: /stylesheets
#   static_dir: stylesheets

# Serve images as static resources.
# - url: /(.+\.(gif|png|jpg))$
#   static_files: \1
#   upload: .+\.(gif|png|jpg)$

# Serve your app through a front controller at index.php or public/index.php.
- url: .*
  script: auto

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  GOOGLE_STORAGE_BUCKET: digiternak1
  CLOUDSQL_CONNECTION_NAME: mysql:unix_socket=/cloudsql/digiternak-420314:us-central1:digiternak-instance
  CLOUDSQL_USER: root
  CLOUDSQL_PASSWORD: t=Rk'zf_+_%9o@H3
  CLOUDSQL_DATABASE_NAME: digiternak

entrypoint: serve web/index.php

runtime_config:
  document_root: web