runtime: php82

runtime_config:
  document_root: web

handlers:
# # Serve a directory as a static resource.
# - url: /stylesheets
#   static_dir: stylesheets

# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$

# Serve your app through a front controller at index.php or public/index.php.
- url: .*
  script: auto

entrypoint: serve web/index.php

# instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  GOOGLE_STORAGE_BUCKET: digiternak1
  CLOUDSQL_PUBLIC_IP: 34.27.91.110
  CLOUDSQL_USER: digiternak
  CLOUDSQL_PASSWORD: digiternak123
  CLOUDSQL_DATABASE_NAME: digiternak
  COOKIE_VALIDATION_KEY: AsmXcRvr0JV5YEbMzsMuZ6yhpA0w7MqP
  MAILER_DSN: smtp://digiternak@gmail.com:ltfs%20ducm%20mbaa%20siwj@smtp.gmail.com:587